<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="DESKTOP-ORN1KTG" failures="1" tests="1" name="com.testRunnersTestNG.TestNGTestRunner" time="65.378" errors="0" timestamp="2023-11-17T18:30:50 IST" skipped="0">
  <testcase classname="com.testRunnersTestNG.TestNGTestRunner" name="runScenario" time="65.378">
    <failure message="expected [true] but found [false]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:819)
at org.testng.Assert.assertEquals(Assert.java:829)
at stepDefinitions.customer.profile.F0003_Profile_edit_page.verify_that_user_should_get_the_respected_message_below_the_name_user_field_or_pop_up_in_profile_update_page(F0003_Profile_edit_page.java:407)
at âœ½.Verify that user should get the respected message below the name user field or pop up in profile update page(file:///C:/Users/Kishor/Desktop/Appium_project/appium_shield/src/test/resources/features/customer/F_Profile_pages/F0003_profile_edit_page.feature:59)
]]>
    </failure>
  </testcase> <!-- runScenario -->
  <system-out/>
</testsuite> <!-- com.testRunnersTestNG.TestNGTestRunner -->
